### ISSUE TITLE
Local testing Checklist

### ISSUE THREAD

**Issue by RosaWagner** [Etcetera-Type-Co/Epilogue#10]
Since your fonts of different formats have the same naming, you will have to test formats one by one, restarting the computer between each to avoid cache issues and conflicts.

### Installation
- [x] No conflict during installation (in user fonts folder: user/Library/Fonts)
- [x] Fonts appear in Fontbook
- [x] Fonts looks good in Fontbook

#### External office app : MS Word*, LibreOffice…
- [x] Upright fonts appear in alphabetical order in dropdown menu
- [x] VF : At least 1 instance appear in dropdown menu (font-origin)
- [x] Style linking works properly (bold and italic button or regular, italic button for all other cuts)
- [x] Fonts are displayed correctly (basic alphabet)
- [x] Kerning has compiled (just display few kerning pairs to see if it works, also using letters with components)

#### External layout app : Adobe Indesign, Affity…
- [x] All styles appear in weight order in dropdown menu
- [x] Fonts are displayed correctly
- [x] All Opentype Features work properly (activation from menu or style)
- [x] VF: must be tested in Illustrator and Indesign at least

#### Primary app : TextEdit
- [x] Font appear in font dropdown menu, all styles appear in style dropdown menu (order looks random)
- [x] Style linking works properly
- [x] Fonts are displayed correctly

(!) In **MS Word**, kerning is applied to the text _as an option_, it is not a parameter that you activate for all your documents. You find it in the advanced parameters of Fonts settings: you have to check the box and specify a minimum text size to apply kerning (5pt for Mac and 8pt for Windows).
(!)(!) **MS Word** creates a fake bold and a fake italic when style linking is absent or not working properly. 
(!)(!)(!) If you had a different naming for TTF or variable font, you would have also check their compatibility : install them all and test them at the same time in the app.
(!)(!)(!)(!) Don't forget to remove fonts from fonts folder at the end of testing.

### Installation
- [x] No conflict during installation
- [x] Fonts appear in C://Fonts folder

Double-click on each cut and check if:
- [x] Outline type is correct (PS for .otf, TT for .ttf)
- [x] Font is digitally signed
- [x] Font is displayed correctly (small size in waterfall)

#### Office app : MS Word
- [x] Upright fonts appear in alphabetical order in dropdown menu
- [x] VF : At least 1 instance appear in dropdown menu (font-origin)
- [x] Style linking works properly (bold and italic button or regular, italic button for all other cuts)
- [x] Fonts are displayed correctly (basic alphabet)
- [x] Kerning has compiled (just display few kerning pairs to see if it works)

## Hinting (from 9-10ppm to 50ppm)
- You can use image-waterfall generated by diffbrowser (if you have gftools-qa installed)
- If you use a html page: display in in firefox or chrome on a normal resolution screen (higher than HD is probably not very useful)
- Check hinting on Widows for truetype fonts, on Mac for postscript fonts
 
- Since hinting is managed by fontmake, there is not much to do except looking if the font is better with or without hinting. For that you can use [GF Regression](http://35.238.63.0) and upload 2 versions of generated font (hinted and unhinted).

You can still check what hinting is made for:
- [ ] All glyphs are well aligned: if you see your /r higher than other letter, it is probably because top point is out of the blue zone. So checks where your guidelines normally are (baseline, x-height, caps-height, ascenders, descenders)
- [ ] Superior and inferiors figures are well aligned too with each other.
- [ ] No overshoot until 48-50ppm 
- [ ] Glyphs are aligned also between styles (bold is not higher than Regular at the same ppm size)
- [ ] Glyphset is consistent (there is no glyph better or worse than the other)
- [ ] Letters are readable 
- [ ] Weight is equally distributed (horizontally and vertically) in symmetrical letters (o, e g, c)
- [ ] Spacing is not messed up
- [ ] Accents don't clash with letters
- [ ] Counter-shaped are not closed (e, g, ring)
- [ ] Upright and italic of the same weight have a consistent weight
- [ ] Dots on /i and /j are aligned

#### Platforms (handy for VF)
- [FontDrop](https://fontdrop.info)
- [Wakamai Fondue](https://wakamaifondue.com)
- [Impallari testing page](http://www.rosaliewagner.com/font-testing/index.php)
- [Axis praxis](https://www.axis-praxis.org/specimens/__DEFAULT__) and [Samsa](https://www.axis-praxis.org/samsa/)
- [Dinamo font gautlet](https://dinamodarkroom.com/gauntlet/)

#### App/tool:
- [Font Goggles](https://fontgoggles.org)
- [DTL OT Master](https://www.fontmaster.nl/index.php/otmaster/)
- [Font table viewer](https://glyphsapp.com/tools/fonttableviewer) (for static fonts)
- [Fontproof](https://github.com/silnrsi/fontproof) (still in development)

**Comment by sursly** [comment]
Hey, is this assigned to me? I have no windows computer to test things on, sadly.

**Comment by RosaWagner** [comment]
You do for Mac, I will do for windows ;) And if ever you have a virtual machine at some point, you will have the checklist.

**Comment by RosaWagner** [comment]
Ah and since Google Fonts only distribute TTF, you can test the ttf also on web-app on Mac.

**Comment by sursly** [comment]
Thanks, got it!

**Comment by RosaWagner** [comment]
I wrote everything, but the most important part is installation, features in indesign, display on Word, display on web. Complete testing should take 2 to 3 hours max. If you make a little change and re-generate a font you tested before, just check if Word can display it (if it works there, it works everywhere) 😅

**Comment by sursly** [comment]
Just commenting here that my mind is blown that I have to turn on kerning in Word. It worked (looked pretty rough before I did that, though). Powerpoint kerning is not working, but I won't worry about that now.
