### ISSUE TITLE
Checklist for figures, punctuation and symbols

### ISSUE THREAD

**Issue by RosaWagner** [Etcetera-Type-Co/Epilogue#2]
This is to resume what we talked about during our meeting, so you have a roadmap ;) Have fun!
_I repeat, nothing here is a universal and static truth, these are conventions (some of them are debatable) that you chose to follow or not._

### Issues with Epilogue
- [x] Math symbols have different width
- [x] Asciicircum is too small
- [x] Asciitilde differs too much from tilde shape
- [x] Copyright, Registered and TradeMark are inconsistent (but it is not such an issue)
- [x] Exclamdown and questiondown are not well positioned for base-glyph
- [x] Upper dot of colon and semi colon is too high in the thin master
- [x] Wrong quotesinglbase and quotedblbase
- [x] Only one zeroslash
- [x] Sups and Sub are too small and too narrow.
- [x] 6 and 9 don't look like they are from the same set

### General advices
- **Math symbol width:** It can become handy to give to arithmetical math symbols the same width as tabular figures, but not mandatory. Or at least the same width, if not the same as tabular figures.
- **Period, comma, colon and semi colon:** It is a detail and honestly I don't see it often, but it can become handy in some cases for them to have an equal width, but not the same as the tabular figures of course. 
- **Spanish punctuation:** bottom exclamdown and questiondown should be aligned with descender line, for the top to not goes too much over the x-height / or top should be aligned with x-height (depends on your design)
- **quotesinglbase and quotedblbase:** they are the same as quote/singl-dbl/right but positioned as a comma
- **Zero slash:** If you have a zeroslash in lining figures, it can be nice to have it in tabular figures too.
- **Sub and sups figures:** a nice compromise can be found for superscripts to fit Caps, ascenders and x-height lowercases. Sups and Nominators can be aligned, although you often see Sups aligned higher (in any case, it is nice to see nominators aligned with lining figures). Denominators are on the baseline, subscripts cross the baseline. They all have the same size, so only one set is made of decomposed path, the other are composites.
- **(c), (R), TM**: different possible strategies for these one. Conventional positioning is: Registered and Trademarks are raised, and copyright not. But we often see Copyright used just as Registred and vice-versa. Also, they are often use in mention in small text size, and would required a bigger version to still be visible. So you could (1) have them small in base glyphs, and big with case sensitive feature, (2) bigger in base glyphs and small with a superscript feature, (3) base glyphs follow conventional use and you may give a superscript feature to (c) and (r). To check in other fonts but I don't think they need to be slanted in italics.
- **6 and 9**: they traditionally have a symmetrical outline with optical adjustment if needed, or at least similar proportions and terminaisons. 
- **Other Sups and Sub:** You can make life easier for educational publishers by adding those signs to the features : ()+-
- **Case sensitive feature** (and so scmall caps feature): hyphen and related glyphs, bullet and related glyphs, parenthesis and related glyphs, exclam and question down, guillemets.
- **Tabular figures**: you can add the currencies to tabular figures, as for some punctuation and, if they are not already with equal width, math symbols. But it really depends on how you plan the font to be used.

**Comment by sursly** [comment]
OK I just pushed out a new update that should clear most of this (and the other issues). It contains several commits at various points, so there's a lot to look at.
