### ISSUE TITLE
Checklist for proportions

### ISSUE THREAD

**Issue by RosaWagner** [Etcetera-Type-Co/Epilogue#4]
This is to resume what we talked about during our meeting, so you have a roadmap ;) Have fun!
_I repeat, nothing here is a universal and static truth, these are conventions (some of them are debatable) that you chose to follow or not._

### Issues with Epilogue
- [x] Some uppercases or either too narrow, either to wide
- [x] Small caps or either too small, either too narrow
- [x] Some lowercases or either too narrow, either too wide
- [x] Overshoots in black master are too small 
- [x] Germandbls is stylish but not sure if so sharp is a good option
- [x] Design space is very wide creating weird contrast in intermediate weight… need another master ?

### Sources
- [Lucas de Groot article about capital german double s](https://www.lucasfonts.com/learn/1E9E)

**Comment by sursly** [comment]
I completely redid the small caps in the update that I just pushed. Much improved in my opinion. I actually think I did almost all of this list above, except the additional middle master we talked about. That said, I made bracket styles for M, N, and W, which I think helps with some of the weird contrast that was going on.

**Comment by RosaWagner** [comment]
It is indeed much improved :) I will review it before our meeting tomorrow. We will have to run some test with the bracket trick, I noted an issue with the kerning last time I used Fontmake for a font with bracket layers. It will be a nice way to see if the issue can be replicated and see if it needs to be fixed or not.

**Comment by RosaWagner** [comment]
Since there is a regular master now, could be a nice opportunity to resolve the thin horizontal stem in intermediate weights ;)

**Comment by sursly** [comment]
Yeah I've been doing that, hopefully it shows (if not, I need to do it better, I guess).

**Comment by RosaWagner** [comment]
All good here now :)
